#!/usr/bin/env python3
from dataclasses import dataclass
from enum import Enum, auto
from urllib import request

NAMESPACE = "wmap@wmap.dev"

class Algorithm(Enum):
    RSA = auto()
    ED25519 = auto()

    @classmethod
    def parse(cls, string):
        if string == "ssh-rsa":
            return cls.RSA
        elif string == "ssh-ed25519":
            return cls.ED25519
        else:
            raise "Unknown ssh key algorithm"

    def __str__(self):
        if self == Algorithm.RSA:
            return "ssh-rsa"
        if self == Algorithm.ED25519:
            return "ssh-ed25519"


@dataclass
class AuthorizedKey:
    algorithm: Algorithm
    material: str
    comment: str

    @classmethod
    def parse(cls, string):
        parts = string.split()
        algorithm = Algorithm.parse(parts[0])
        return cls(algorithm, parts[1], " ".join(parts[2:]))

    def into_allowed_signer(self, profile):
        principal = profile.url
        algorithm = str(self.algorithm)
        material = self.material
        return f"{principal} namespaces=\"{NAMESPACE}\" {algorithm} {material}"


@dataclass
class Profile:
    url: str

    def authorized_keys_url(self):
        return self.url + ".keys"

    def authorized_keys(self):
        with request.urlopen(self.authorized_keys_url()) as response:
            lines = response.read().decode().splitlines()
            return [AuthorizedKey.parse(line) for line in lines]

    def allowed_signers(self):
        return [k.into_allowed_signer(self) for k in self.authorized_keys()]

if __name__ == "__main__":
	print("Hello")
