#!/usr/bin/env python3
from dataclasses import dataclass
from enum import Enum, auto
from urllib import request
import base64
import subprocess
import tempfile


NAMESPACE = "wmap@wmap.dev"


class Algorithm(Enum):
    RSA = auto()
    ED25519 = auto()

    @classmethod
    def parse(cls, string):
        if string == "ssh-rsa":
            return cls.RSA
        elif string == "ssh-ed25519":
            return cls.ED25519
        else:
            raise "Unknown ssh key algorithm"

    def __str__(self):
        if self == Algorithm.RSA:
            return "ssh-rsa"
        if self == Algorithm.ED25519:
            return "ssh-ed25519"


@dataclass
class AuthorizedKey:
    algorithm: Algorithm
    material: str
    comment: str

    @classmethod
    def parse(cls, string):
        parts = string.split()
        algorithm = Algorithm.parse(parts[0])
        return cls(algorithm, parts[1], " ".join(parts[2:]))

    def into_allowed_signer(self, profile):
        principal = profile.url
        algorithm = str(self.algorithm)
        material = self.material
        return f"{principal} namespaces=\"{NAMESPACE}\" {algorithm} {material}"


@dataclass
class Profile:
    url: str

    def authorized_keys_url(self):
        return self.url + ".keys"

    def authorized_keys(self):
        with request.urlopen(self.authorized_keys_url()) as response:
            lines = response.read().decode().splitlines()
            return [AuthorizedKey.parse(line) for line in lines]

    def allowed_signers(self):
        return [k.into_allowed_signer(self) for k in self.authorized_keys()]

    def verify_signed_data(self, data, signature_path):
        with tempfile.NamedTemporaryFile() as asf:
            signers = "\n".join(self.allowed_signers()) + "\n"
            asf.write(bytes(signers, 'utf-8'))
            asf.flush()
            results = subprocess.run([
                'ssh-keygen', '-Y', 'verify',
                '-f', asf.name,
                '-I', self.url,
                '-n', NAMESPACE,
                '-s', signature_path
            ], input=data)
            return results.returncode == 0


@dataclass
class PrivateKey:
    profile: Profile
    path: str

    def sign(self, file):
        subprocess.run([
            'ssh-keygen', '-Y', 'sign',
            '-f', self.path,
            '-n', NAMESPACE,
            file
        ])


@dataclass
class Signature:
    content: str

    @classmethod
    def load(cls, path):
        with open(path) as f:
            content = str(base64.b64encode(bytes(f.read(), 'utf-8')), 'utf-8')
            return cls(content)

    def dump(self, path):
        with open(path, 'w') as f:
            decoded = str(base64.b64decode(self.content), 'utf-8')
            f.write(decoded)


if __name__ == "__main__":  # pragma: no cover
    print("Hello")
