name: Test Suite

on: push

jobs:
  test:
    strategy:
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3
      
    - name: make test
      run: make test
