name: Tests

on: push

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3

    - name: Git version
      run: git --version

    - name: Run Tests
      run: prove
