name: Tests

on: push

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-18.04, windows-2016, windows-2019, windows-2022]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3

    - name: Run Tests
      run: make test
