name: Test Suite

on:
  push:
    branches:
      - "*"

jobs:
  test:
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3
    - run: make test
